# .github/workflows/deploy.yml
name: Deploy and Scan

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write # For GitHub Security tab
  id-token: write # For AWS OIDC

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }}

      # Vulnerability Scanning with JSON output for Security Hub
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: ${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }}
          format: 'json'
          output: 'vuln-results.json'
          severity: 'CRITICAL,HIGH'
      # Convert to Security Hub format
      - name: Convert to Security Hub format
        run: |
          cat > findings.json << EOF
          {
            "Findings": [
              {
                "SchemaVersion": "2018-10-08",
                "Id": "trivy-$(date +%s)",
                "ProductArn": "arn:aws:securityhub:${AWS_REGION}:${AWS_ACCOUNT_ID}:product/aquasec/aquasec",
                "GeneratorId": "Trivy",
                "AwsAccountId": "${AWS_ACCOUNT_ID}",
                "Types": [ "Software and Configuration Checks" ],
                "CreatedAt": "$(date --utc +%Y-%m-%dT%H:%M:%S.%3NZ)",
                "UpdatedAt": "$(date --utc +%Y-%m-%dT%H:%M:%S.%3NZ)",
                "Severity": {
                  "Label": "HIGH"
                },
                "Title": "Container Image Vulnerabilities",
                "Description": "$(cat vuln-results.json | jq -c -r .)",
                "Resources": [
                  {
                    "Type": "Container",
                    "Id": "${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }}",
                    "Region": "${AWS_REGION}"
                  }
                ]
              }
            ]
          }
          EOF
        env:
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      # Infrastructure as Code Scanning
      - name: Run Trivy IaC scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'json'
          output: 'iac-results.json'
          severity: 'CRITICAL,HIGH'
        # env:
        #   AWS_REGION: us-east-1
        #   AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      # SBOM Generation
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'cyclonedx'
          output: 'sbom-results.json'
          # github-pat: ${{ secrets.GITHUB_TOKEN }}
      # Convert findings for Security Hub
      - name: Prepare Security Hub findings
        run: |
          cat > findings.json << EOF
          {
            "Findings": [
              {
                "SchemaVersion": "2018-10-08",
                "Id": "trivy-vuln-$(date +%s)",
                "ProductArn": "arn:aws:securityhub:${AWS_REGION}:${AWS_ACCOUNT_ID}:product/aquasec/aquasec",
                "GeneratorId": "Trivy",
                "AwsAccountId": "${AWS_ACCOUNT_ID}",
                "Types": [ "Software and Configuration Checks/Vulnerabilities" ],
                "CreatedAt": "$(date --utc +%Y-%m-%dT%H:%M:%S.%3NZ)",
                "UpdatedAt": "$(date --utc +%Y-%m-%dT%H:%M:%S.%3NZ)",
                "Severity": { "Label": "HIGH" },
                "Title": "Container Image Vulnerabilities",
                "Description": "$(cat vuln-results.json | jq -c -r .)",
                "Resources": [
                  {
                    "Type": "Container",
                    "Id": "${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }}",
                    "Region": "${AWS_REGION}"
                  }
                ]
              },
              {
                "SchemaVersion": "2018-10-08",
                "Id": "trivy-iac-$(date +%s)",
                "ProductArn": "arn:aws:securityhub:${AWS_REGION}:${AWS_ACCOUNT_ID}:product/aquasec/aquasec",
                "GeneratorId": "Trivy",
                "AwsAccountId": "${AWS_ACCOUNT_ID}",
                "Types": [ "Software and Configuration Checks/Infrastructure Code Scan" ],
                "CreatedAt": "$(date --utc +%Y-%m-%dT%H:%M:%S.%3NZ)",
                "UpdatedAt": "$(date --utc +%Y-%m-%dT%H:%M:%S.%3NZ)",
                "Severity": { "Label": "HIGH" },
                "Title": "Infrastructure as Code Findings",
                "Description": "$(cat iac-results.json | jq -c -r .)",
                "Resources": [
                  {
                    "Type": "Other",
                    "Id": "IaC-Scan-${{ github.sha }}",
                    "Region": "${AWS_REGION}"
                  }
                ]
              }
            ]
          }
          EOF
        env:
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      # Upload results to Security Hub
      - name: Import findings to Security Hub
        run: |
          aws securityhub batch-import-findings --findings file://findings.json

      # Upload SBOM as artifact
      - name: Upload SBOM Report
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom-results.json
          retention-days: 90

      # Also generate SARIF for GitHub Security tab
      - name: Run Trivy for GitHub Security Tab
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      # Deploy if all checks pass
      - name: Deploy to ECS
        if: success()
        run: |
          aws ecs update-service --cluster demo-cluster --service demo-service --force-new-deployment
