# .github/workflows/deploy.yml
name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write # Github Security
  id-token: write # AWS OIDC

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download ASFF template
      - name: Download ASFF template
        run: |
          mkdir -p templates
          curl -o templates/asff.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/asff.tpl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }}

      # Vulnerability Scanning
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: '${{ steps.login-ecr.outputs.registry }}/demo-app:${{ github.sha }}'
          format: 'template'
          template: '@templates/asff.tpl'
          output: 'report.asff'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln'  # Disable secret scanning for speed
        env:
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      # IaC Scanning
      - name: Run Trivy IaC scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'template'
          template: '@templates/asff.tpl'
          output: 'iac-report.asff'
          severity: 'CRITICAL,HIGH'
        env:
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      # Upload results to Security Hub
      - name: Import vulnerability findings to Security Hub
        if: always()
        run: |
          if [ -f "report.asff" ]; then
            aws securityhub batch-import-findings --findings "file://report.asff"
          fi

      - name: Import IaC findings to Security Hub
        if: always()
        run: |
          if [ -f "iac-report.asff" ]; then
            aws securityhub batch-import-findings --findings "file://iac-report.asff"
          fi

      # Generate SARIF for GitHub Security tab
      - name: Run Trivy for GitHub Security Tab
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln'  # Disable secret scanning for speed

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      # Deploy if all checks pass
      - name: Deploy to ECS
        if: success()
        run: |
          aws ecs update-service --cluster demo-cluster --service demo-service --force-new-deployment
